#!/usr/bin/env bash

cd ..

if [ -d kagi-usage-extension ]; then
	rm -rf ~/.local/share/gnome-shell/extensions/github@drsr.io
	cp -r kagi-usage-extension ~/.local/share/gnome-shell/extensions/github@drsr.io 
	cd ~/.local/share/gnome-shell/extensions/github@drsr.io/schemas
	glib-compile-schemas .
	gnome-session-quit --no-prompt
else
	echo "Extension folder not found"
fi
